version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Performing manual install of compose cli"
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
  pre_build:
    commands:
      - echo Logging in to Docker Hub...

  build:
    commands:
      - echo Build started on `date`
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -input=false
      - terraform apply -input=false -auto-approve -var='AWS_ACCESS_KEY=$AWS_ACCESS_KEY' -var='AWS_SECRET_KEY=$AWS_SECRET_KEY' -var='INTEGRATION_HOST=$INTEGRATION_HOST'
  
  post_build:
    commands:
      - echo "Terraform completed on `date`"

  post_build:
    commands:

artifacts:
  files:
    - '**/*'