version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12

  build:
    commands:
      - echo Build started on `date`
      - cd "$CODEBUILD_SRC_DIR"
      - ls -al
  
  post_build:
    commands:
      - echo "Tests completed on `date`"

  post_build:
    commands:

artifacts:
  files:
    - '**/*'
