version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Install terraform"
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"

  build:
    commands:
      - echo Build started on `date`
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -input=false
      - TF_VAR_AWS_ACCESS_KEY=$AWS_ACCESS_KEY TF_VAR_AWS_SECRET_KEY=$AWS_SECRET_KEY TF_VAR_INTEGRATION_HOST=$INTEGRATION_HOST terraform apply -input=false -auto-approve